### ISSUE TITLE
Allow user to configure what the filename pattern should be

### ISSUE THREAD

**Issue by trainiac** [presidenten/webpack-context-vuex-hmr#1]
Awesome work.  Thank you.

I'd like to submit a PR but wanted to run it by the repo manager first. 

In the documentation you have this line 

```js
/-store.js|-substore.js$/              // [edit me]  regexp to find modules
```
This great but if I want to change that to say

```js
/-foo.js$/
```

`getModules` and `setupHMR` don't work because of these lines.
https://github.com/presidenten/webpack-context-vuex-hmr/blob/master/src/importer.js#L50
https://github.com/presidenten/webpack-context-vuex-hmr/blob/master/src/importer.js#L19

Shouldn't we just remove those checks?  The regex you pass to ContextReplacementPlugin should be responsible for making sure you get the right files, correct?

**Comment by presidenten** [comment]
Yeah, I think you are right... Actually, now that you mentioned it, I realize that `/-store.js|-substore.js$/ ` is kind of old as well. 
I dont think we need load the substores at all. I mean, I do filter them out first chance I get.

Just tried to run with `/-store.js$/` in the demo project, and the hmr seems to work just fine in both stores and substores. 

Nice finding! 

Feel free to do your PR, I'll merge it. Maybe you could update the regex in the readme while you are at it and skip the -substore bit?

`<shameless-plug>`
Also, if you like this, you should checkout the [vuex+ repo](https://github.com/presidenten/vuex-plus) as well. It helps with creating instances and deciding when to share state and if the instances should persist or not. Its setting up the hmr through this package under the hood.
Would be awesome to have a pair of extra eyes checking the code. ;-)
Its still under development, but Im hoping to reach 1.0.0 in a few weeks since I need it for production really soon. I just started to write tests in jest and noticed a few bugs that Ill fix during the weekend.
`</shameless-plug>`

**Comment by trainiac** [comment]
OK! will do. I'll update the docs as well. I'll checkout vuex-plus as well. Thanks!

**Comment by presidenten** [comment]
Nice! Please do! 
I try to update the corresponding example project as the library is being developed, together with a tutorial to explain everything.
 I think that is the best starting point [guide/example here](https://github.com/presidenten/vuex-plus-demo)

**Comment by presidenten** [comment]
Its now merged and published as 2.1.1. 
Demo project is also updated and hmr is verified with new regex matchings for stores.

Thanks for the PR!

**Comment by trainiac** [comment]
No problem! I just took a look at vuex-plus, would love to chat about that maybe on Gitter? https://gitter.im/vuejs/vue or I could send you an email.

**Comment by presidenten** [comment]
Sure, starting convo on gitter.
